---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-ide-web
    apps: cloud-ide
  name: cloud-ide-web
  namespace: cloud-ide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ide-web
  template:
    metadata:
      labels:
        app: cloud-ide-web
    spec:
      containers:
      - name: web
        image: cloud-ide-webserver:v1.0
        args:
          - -mode              # 指定运行模式
          - release
          - -mysql-datasource  # 指定mysql datasource
          - root:123456@(cloud-ide-mysql-svc:3306)/cloudcode?charset=utf8mb4&parseTime=true&loc=Local
          - -log-level         # 指定日志等级
          - error
          - -email-enabled     # 是否启动email注册验证
          - disabled
          - grpc-addr          # 指定grpc地址，即control-plane的service和port
          - cloud-ide-control-plane-svc:6387
        ports:
        - containerPort: 8088
        resources:
          requests:
            cpu: "0.5"
            memory: "128Mi"
          limits:
            cpu: "2"
            memory: "512Mi"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-ide-web-svc
    apps: cloud-ide
  name: cloud-ide-web-svc
  namespace: cloud-ide
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: cloud-ide-web
  type: ClusterIP

