apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-ide-control-plane-role
  namespace: cloud-ide-ws
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - cloud-ide.mangohow.com
    resources:
      - workspaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloud-ide.mangohow.com
    resources:
      - workspaces/finalizers
    verbs:
      - update
  - apiGroups:
      - cloud-ide.mangohow.com
    resources:
      - workspaces/status
    verbs:
      - get
      - patch
      - update

