// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: pb/proto/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCreate_Status int32

const (
	ResponseCreate_Success      ResponseCreate_Status = 0
	ResponseCreate_AlreadyExist ResponseCreate_Status = 1
	ResponseCreate_Error        ResponseCreate_Status = 2
)

// Enum value maps for ResponseCreate_Status.
var (
	ResponseCreate_Status_name = map[int32]string{
		0: "Success",
		1: "AlreadyExist",
		2: "Error",
	}
	ResponseCreate_Status_value = map[string]int32{
		"Success":      0,
		"AlreadyExist": 1,
		"Error":        2,
	}
)

func (x ResponseCreate_Status) Enum() *ResponseCreate_Status {
	p := new(ResponseCreate_Status)
	*p = x
	return p
}

func (x ResponseCreate_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCreate_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_service_proto_enumTypes[0].Descriptor()
}

func (ResponseCreate_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_service_proto_enumTypes[0]
}

func (x ResponseCreate_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCreate_Status.Descriptor instead.
func (ResponseCreate_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{2, 0}
}

type ResponseStart_Status int32

const (
	ResponseStart_Success  ResponseStart_Status = 0
	ResponseStart_NotFound ResponseStart_Status = 1
	ResponseStart_Error    ResponseStart_Status = 2
)

// Enum value maps for ResponseStart_Status.
var (
	ResponseStart_Status_name = map[int32]string{
		0: "Success",
		1: "NotFound",
		2: "Error",
	}
	ResponseStart_Status_value = map[string]int32{
		"Success":  0,
		"NotFound": 1,
		"Error":    2,
	}
)

func (x ResponseStart_Status) Enum() *ResponseStart_Status {
	p := new(ResponseStart_Status)
	*p = x
	return p
}

func (x ResponseStart_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStart_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_service_proto_enumTypes[1].Descriptor()
}

func (ResponseStart_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_service_proto_enumTypes[1]
}

func (x ResponseStart_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStart_Status.Descriptor instead.
func (ResponseStart_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{4, 0}
}

type ResponseStop_Status int32

const (
	ResponseStop_Success  ResponseStop_Status = 0
	ResponseStop_NotFound ResponseStop_Status = 1
	ResponseStop_Error    ResponseStop_Status = 2
)

// Enum value maps for ResponseStop_Status.
var (
	ResponseStop_Status_name = map[int32]string{
		0: "Success",
		1: "NotFound",
		2: "Error",
	}
	ResponseStop_Status_value = map[string]int32{
		"Success":  0,
		"NotFound": 1,
		"Error":    2,
	}
)

func (x ResponseStop_Status) Enum() *ResponseStop_Status {
	p := new(ResponseStop_Status)
	*p = x
	return p
}

func (x ResponseStop_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStop_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_service_proto_enumTypes[2].Descriptor()
}

func (ResponseStop_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_service_proto_enumTypes[2]
}

func (x ResponseStop_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStop_Status.Descriptor instead.
func (ResponseStop_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{6, 0}
}

type ResponseDelete_Status int32

const (
	ResponseDelete_Success ResponseDelete_Status = 0
	ResponseDelete_Error   ResponseDelete_Status = 1
)

// Enum value maps for ResponseDelete_Status.
var (
	ResponseDelete_Status_name = map[int32]string{
		0: "Success",
		1: "Error",
	}
	ResponseDelete_Status_value = map[string]int32{
		"Success": 0,
		"Error":   1,
	}
)

func (x ResponseDelete_Status) Enum() *ResponseDelete_Status {
	p := new(ResponseDelete_Status)
	*p = x
	return p
}

func (x ResponseDelete_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseDelete_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_service_proto_enumTypes[3].Descriptor()
}

func (ResponseDelete_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_service_proto_enumTypes[3]
}

func (x ResponseDelete_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseDelete_Status.Descriptor instead.
func (ResponseDelete_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{8, 0}
}

type ResponseRunningWorkspace_Status int32

const (
	ResponseRunningWorkspace_Success  ResponseRunningWorkspace_Status = 0
	ResponseRunningWorkspace_NotFound ResponseRunningWorkspace_Status = 1
)

// Enum value maps for ResponseRunningWorkspace_Status.
var (
	ResponseRunningWorkspace_Status_name = map[int32]string{
		0: "Success",
		1: "NotFound",
	}
	ResponseRunningWorkspace_Status_value = map[string]int32{
		"Success":  0,
		"NotFound": 1,
	}
)

func (x ResponseRunningWorkspace_Status) Enum() *ResponseRunningWorkspace_Status {
	p := new(ResponseRunningWorkspace_Status)
	*p = x
	return p
}

func (x ResponseRunningWorkspace_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseRunningWorkspace_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_service_proto_enumTypes[4].Descriptor()
}

func (ResponseRunningWorkspace_Status) Type() protoreflect.EnumType {
	return &file_pb_proto_service_proto_enumTypes[4]
}

func (x ResponseRunningWorkspace_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseRunningWorkspace_Status.Descriptor instead.
func (ResponseRunningWorkspace_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{10, 0}
}

// 工作空间的资源限制
type ResourceLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu     string `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory  string `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage string `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *ResourceLimit) Reset() {
	*x = ResourceLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimit) ProtoMessage() {}

func (x *ResourceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimit.ProtoReflect.Descriptor instead.
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimit) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceLimit) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceLimit) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

// 创建请求
type RequestCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid             string         `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid             string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Image           string         `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Port            int32          `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	GitRepository   string         `protobuf:"bytes,5,opt,name=gitRepository,proto3" json:"gitRepository,omitempty"`
	VolumeMountPath string         `protobuf:"bytes,6,opt,name=volumeMountPath,proto3" json:"volumeMountPath,omitempty"`
	ResourceLimit   *ResourceLimit `protobuf:"bytes,7,opt,name=resourceLimit,proto3" json:"resourceLimit,omitempty"`
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *RequestCreate) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *RequestCreate) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RequestCreate) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RequestCreate) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestCreate) GetGitRepository() string {
	if x != nil {
		return x.GitRepository
	}
	return ""
}

func (x *RequestCreate) GetVolumeMountPath() string {
	if x != nil {
		return x.VolumeMountPath
	}
	return ""
}

func (x *RequestCreate) GetResourceLimit() *ResourceLimit {
	if x != nil {
		return x.ResourceLimit
	}
	return nil
}

type ResponseCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseCreate_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ResponseCreate_Status" json:"status,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseCreate) Reset() {
	*x = ResponseCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreate) ProtoMessage() {}

func (x *ResponseCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreate.ProtoReflect.Descriptor instead.
func (*ResponseCreate) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseCreate) GetStatus() ResponseCreate_Status {
	if x != nil {
		return x.Status
	}
	return ResponseCreate_Success
}

func (x *ResponseCreate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid           string         `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid           string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceLimit *ResourceLimit `protobuf:"bytes,3,opt,name=resourceLimit,proto3" json:"resourceLimit,omitempty"`
}

func (x *RequestStart) Reset() {
	*x = RequestStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStart) ProtoMessage() {}

func (x *RequestStart) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStart.ProtoReflect.Descriptor instead.
func (*RequestStart) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *RequestStart) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *RequestStart) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RequestStart) GetResourceLimit() *ResourceLimit {
	if x != nil {
		return x.ResourceLimit
	}
	return nil
}

// 工作空间运行信息
type ResponseStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseStart_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ResponseStart_Status" json:"status,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseStart) Reset() {
	*x = ResponseStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStart) ProtoMessage() {}

func (x *ResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStart.ProtoReflect.Descriptor instead.
func (*ResponseStart) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseStart) GetStatus() ResponseStart_Status {
	if x != nil {
		return x.Status
	}
	return ResponseStart_Success
}

func (x *ResponseStart) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RequestStop) Reset() {
	*x = RequestStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStop) ProtoMessage() {}

func (x *RequestStop) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStop.ProtoReflect.Descriptor instead.
func (*RequestStop) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *RequestStop) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *RequestStop) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ResponseStop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseStop_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ResponseStop_Status" json:"status,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseStop) Reset() {
	*x = ResponseStop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStop) ProtoMessage() {}

func (x *ResponseStop) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStop.ProtoReflect.Descriptor instead.
func (*ResponseStop) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseStop) GetStatus() ResponseStop_Status {
	if x != nil {
		return x.Status
	}
	return ResponseStop_Success
}

func (x *ResponseStop) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RequestDelete) Reset() {
	*x = RequestDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelete) ProtoMessage() {}

func (x *RequestDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelete.ProtoReflect.Descriptor instead.
func (*RequestDelete) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *RequestDelete) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *RequestDelete) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ResponseDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseDelete_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pb.ResponseDelete_Status" json:"status,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseDelete) Reset() {
	*x = ResponseDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDelete) ProtoMessage() {}

func (x *ResponseDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDelete.ProtoReflect.Descriptor instead.
func (*ResponseDelete) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseDelete) GetStatus() ResponseDelete_Status {
	if x != nil {
		return x.Status
	}
	return ResponseDelete_Success
}

func (x *ResponseDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestRunningWorkspaces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *RequestRunningWorkspaces) Reset() {
	*x = RequestRunningWorkspaces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRunningWorkspaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRunningWorkspaces) ProtoMessage() {}

func (x *RequestRunningWorkspaces) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRunningWorkspaces.ProtoReflect.Descriptor instead.
func (*RequestRunningWorkspaces) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *RequestRunningWorkspaces) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ResponseRunningWorkspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspaces []*ResponseRunningWorkspace_WorkspaceBasicInfo `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
}

func (x *ResponseRunningWorkspace) Reset() {
	*x = ResponseRunningWorkspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRunningWorkspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRunningWorkspace) ProtoMessage() {}

func (x *ResponseRunningWorkspace) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRunningWorkspace.ProtoReflect.Descriptor instead.
func (*ResponseRunningWorkspace) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseRunningWorkspace) GetWorkspaces() []*ResponseRunningWorkspace_WorkspaceBasicInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type ResponseRunningWorkspace_WorkspaceBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ResponseRunningWorkspace_WorkspaceBasicInfo) Reset() {
	*x = ResponseRunningWorkspace_WorkspaceBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRunningWorkspace_WorkspaceBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRunningWorkspace_WorkspaceBasicInfo) ProtoMessage() {}

func (x *ResponseRunningWorkspace_WorkspaceBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRunningWorkspace_WorkspaceBasicInfo.ProtoReflect.Descriptor instead.
func (*ResponseRunningWorkspace_WorkspaceBasicInfo) Descriptor() ([]byte, []int) {
	return file_pb_proto_service_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ResponseRunningWorkspace_WorkspaceBasicInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *ResponseRunningWorkspace_WorkspaceBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pb_proto_service_proto protoreflect.FileDescriptor

var file_pb_proto_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x53, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x22, 0xe6, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x69, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x0d, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x6b,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x31, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x89, 0x01, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x2f, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x33, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x7f, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x2c,
	0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xcc, 0x01, 0x0a,
	0x18, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x12, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x32, 0xb1, 0x02, 0x0a, 0x0f,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x34, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2e,
	0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x4f,
	0x0a, 0x11, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_service_proto_rawDescOnce sync.Once
	file_pb_proto_service_proto_rawDescData = file_pb_proto_service_proto_rawDesc
)

func file_pb_proto_service_proto_rawDescGZIP() []byte {
	file_pb_proto_service_proto_rawDescOnce.Do(func() {
		file_pb_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_service_proto_rawDescData)
	})
	return file_pb_proto_service_proto_rawDescData
}

var file_pb_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pb_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_proto_service_proto_goTypes = []interface{}{
	(ResponseCreate_Status)(0),                          // 0: pb.ResponseCreate.Status
	(ResponseStart_Status)(0),                           // 1: pb.ResponseStart.Status
	(ResponseStop_Status)(0),                            // 2: pb.ResponseStop.Status
	(ResponseDelete_Status)(0),                          // 3: pb.ResponseDelete.Status
	(ResponseRunningWorkspace_Status)(0),                // 4: pb.ResponseRunningWorkspace.Status
	(*ResourceLimit)(nil),                               // 5: pb.ResourceLimit
	(*RequestCreate)(nil),                               // 6: pb.RequestCreate
	(*ResponseCreate)(nil),                              // 7: pb.ResponseCreate
	(*RequestStart)(nil),                                // 8: pb.RequestStart
	(*ResponseStart)(nil),                               // 9: pb.ResponseStart
	(*RequestStop)(nil),                                 // 10: pb.RequestStop
	(*ResponseStop)(nil),                                // 11: pb.ResponseStop
	(*RequestDelete)(nil),                               // 12: pb.RequestDelete
	(*ResponseDelete)(nil),                              // 13: pb.ResponseDelete
	(*RequestRunningWorkspaces)(nil),                    // 14: pb.RequestRunningWorkspaces
	(*ResponseRunningWorkspace)(nil),                    // 15: pb.ResponseRunningWorkspace
	(*ResponseRunningWorkspace_WorkspaceBasicInfo)(nil), // 16: pb.ResponseRunningWorkspace.WorkspaceBasicInfo
}
var file_pb_proto_service_proto_depIdxs = []int32{
	5,  // 0: pb.RequestCreate.resourceLimit:type_name -> pb.ResourceLimit
	0,  // 1: pb.ResponseCreate.status:type_name -> pb.ResponseCreate.Status
	5,  // 2: pb.RequestStart.resourceLimit:type_name -> pb.ResourceLimit
	1,  // 3: pb.ResponseStart.status:type_name -> pb.ResponseStart.Status
	2,  // 4: pb.ResponseStop.status:type_name -> pb.ResponseStop.Status
	3,  // 5: pb.ResponseDelete.status:type_name -> pb.ResponseDelete.Status
	16, // 6: pb.ResponseRunningWorkspace.workspaces:type_name -> pb.ResponseRunningWorkspace.WorkspaceBasicInfo
	6,  // 7: pb.CloudIdeService.createSpace:input_type -> pb.RequestCreate
	8,  // 8: pb.CloudIdeService.startSpace:input_type -> pb.RequestStart
	12, // 9: pb.CloudIdeService.deleteSpace:input_type -> pb.RequestDelete
	10, // 10: pb.CloudIdeService.stopSpace:input_type -> pb.RequestStop
	14, // 11: pb.CloudIdeService.runningWorkspaces:input_type -> pb.RequestRunningWorkspaces
	7,  // 12: pb.CloudIdeService.createSpace:output_type -> pb.ResponseCreate
	9,  // 13: pb.CloudIdeService.startSpace:output_type -> pb.ResponseStart
	13, // 14: pb.CloudIdeService.deleteSpace:output_type -> pb.ResponseDelete
	11, // 15: pb.CloudIdeService.stopSpace:output_type -> pb.ResponseStop
	15, // 16: pb.CloudIdeService.runningWorkspaces:output_type -> pb.ResponseRunningWorkspace
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_proto_service_proto_init() }
func file_pb_proto_service_proto_init() {
	if File_pb_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRunningWorkspaces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRunningWorkspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRunningWorkspace_WorkspaceBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_service_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_service_proto_goTypes,
		DependencyIndexes: file_pb_proto_service_proto_depIdxs,
		EnumInfos:         file_pb_proto_service_proto_enumTypes,
		MessageInfos:      file_pb_proto_service_proto_msgTypes,
	}.Build()
	File_pb_proto_service_proto = out.File
	file_pb_proto_service_proto_rawDesc = nil
	file_pb_proto_service_proto_goTypes = nil
	file_pb_proto_service_proto_depIdxs = nil
}
